# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def wait(self, timeout, method):
        WebDriverWait(self.driver, 10).until(method)

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test22(self):
        self.driver.get("https://testerhome.com/")
        self.driver.set_window_size(1440, 860)
        ele = (By.LINK_TEXT, "社团")
        self.wait(10, expected_conditions.element_to_be_clickable(ele))
        self.driver.find_element(By.LINK_TEXT, "社团").click()
        ele2 = (By.LINK_TEXT, "霍格沃兹测试学院")
        self.wait(10, expected_conditions.element_to_be_clickable(ele2))
        self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院").click()
